Traceback (most recent call last):
  File "/usr/local/bin/rally-ci", line 9, in <module>
    load_entry_point('rallyci==0.1.dev', 'console_scripts', 'rally-ci')()
  File "/usr/local/lib/python3.4/dist-packages/rallyci-0.1.dev-py3.4.egg/rallyci/daemon.py", line 34, in run
  File "/usr/local/lib/python3.4/dist-packages/rallyci-0.1.dev-py3.4.egg/rallyci/root.py", line 121, in load_config
  File "/usr/local/lib/python3.4/dist-packages/rallyci-0.1.dev-py3.4.egg/rallyci/root.py", line 29, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/home/rally/config.yaml'
Traceback (most recent call last):
  File "/usr/local/bin/rally-ci", line 9, in <module>
    load_entry_point('rallyci==0.1.dev', 'console_scripts', 'rally-ci')()
  File "/usr/local/lib/python3.4/dist-packages/rallyci-0.1.dev-py3.4.egg/rallyci/daemon.py", line 34, in run
  File "/usr/local/lib/python3.4/dist-packages/rallyci-0.1.dev-py3.4.egg/rallyci/root.py", line 121, in load_config
  File "/usr/local/lib/python3.4/dist-packages/rallyci-0.1.dev-py3.4.egg/rallyci/root.py", line 29, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '/home/rally/config.yaml'
